### PR TITLE
v1.1.13

### PR DESCRIPTION
**Pull request by drjova**

### CODE REVIEW

**Comment by drjova** [comment]
* remap & reindex literature

**Comment by michamos** [comment]
the bibliography generator has a bug fixed in #1047. I think we should either wait for that to be merged or remove/feature flag the bibliography generator.

**Comment by drjova** [comment]
we're not in rush to deploy this, we could wait

**Comment by drjova** [comment]
I'll close it for now, not to waste resource on travis everytime we commit something

**Pull request merged**
