### PR TITLE
setup: add web_pdb dev dependency

### PR DESCRIPTION
**Pull request by miguelgrc**
This will make it much easier for us to debug inside a docker container.

To use, ``import web_pdb`` and invoke ``web_pdb.set_trace(port=7777)`` where desired. Then go to ``localhost:7777`` to access the debugger.

### CODE REVIEW

**Comment by michamos** [comment]
don't we install dev packages also inside prod containers?

**Comment by pazembrz** [comment]
I didn't noticed this before, but yes, this is true. Why we are doing this?

**Comment by harunurhan** [comment]
why don't we do `--no-dev` while building the image?

**Comment by pazembrz** [comment]
I don't know. Probably we should.

**Comment by harunurhan** [comment]
so we can maybe take this in, because it is useful. And add `--no-dev` to `Dockerfile`s to reduce the size of the images

@drjova @benjamin-bergia

**Comment by drjova** [comment]
We can just create a US for adding ``--no-dev``

**Pull request merged**
