### PR TITLE
ui: change help blog url

### PR DESCRIPTION
**Pull request by harunurhan**
This will break the link until the release (labs/beta becomes master)

INSPIR-3308

### CODE REVIEW

**Comment by michamos** [comment]
This is not urgent at all, as we will redirect `labs.inspirehep.net` -> `inspirehep.net`.

**Comment by harunurhan** [comment]
ah right, then this PR can wait.

**Comment by monaawi** [comment]
why does it need to wait?

**Comment by harunurhan** [comment]
it would break `help` link on `labs ` for no reason.

**Comment by drjova** [comment]
@harunurhan could you please rebase?

**Pull request merged**
