### PR TITLE
ui: add bluesky and mastodon

### PR DESCRIPTION
**Pull request by miguelgrc**
* ref: https://github.com/cern-sis/issues-inspire/issues/619

Also: 
* Bumped `inspire-schemas`
* Many snapshots updated due to the bump to `@ant-design/icons`

Screenshot 2024-12-02 at 16 05 06
Screenshot 2024-12-02 at 16 05 41
Screenshot 2024-12-02 at 16 06 06

### CODE REVIEW

**Comment by drjova** [comment]
@miguelgrc looks good 💯 thanks! It just misses the loader/serializer https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/marshmallow/author.py from the backend :)

**Comment by michamos** [comment]
While you're at it, could you also put X below Bluesky and mastodon (so in that order) everywhere? I expect X usage will be going down in the future in favor of the others.

**Comment by miguelgrc** [comment]
> @miguelgrc looks good 💯 thanks! It just misses the loader/serializer https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/marshmallow/author.py from the backend :)

This also requires changes in `inspire-schemas` [here[(https://github.com/inspirehep/inspire-schemas/blob/1c7b32f35b94d439837b509b6c3951149395c814/inspire_schemas/builders/authors.py#L192), to add `add_bluesky` and `add_mastodon`, right?

**Comment by drjova** [comment]
> > @miguelgrc looks good 💯 thanks! It just misses the loader/serializer https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/marshmallow/author.py from the backend :)
> 
> This also requires changes in `inspire-schemas` [here](https://github.com/inspirehep/inspire-schemas/blob/1c7b32f35b94d439837b509b6c3951149395c814/inspire_schemas/builders/authors.py#L192), to add `add_bluesky` and `add_mastodon`, right?

yes, I will make a pr for that. Thank you!

**Comment by drjova** [comment]
https://github.com/inspirehep/inspire-schemas/pull/471

**Review by drjova — APPROVED** [review]
🚀

**Pull request merged**
